//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.cpp
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#include "Jamnik.h"

string Jamnik::KopanieWZiemie() {

}

string Jamnik::PodazajTropem() {

}

Jamnik Jamnik::Jamnik(float uszy = 1, float ogon = 1) {

}

