//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Jamnik.h
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#if !defined(_JAMNIK_H)
#define _JAMNIK_H

#include "Pies.h"

class Jamnik : public Pies {
public:
	string KopanieWZiemie();
	string PodazajTropem();
	Jamnik Jamnik(float uszy = 1, float ogon = 1);
private:
	float dlugosc_uszu;
	float dlugosc_ogona;
};

#endif  //_JAMNIK_H
