//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#include "Pies.h"

string Pies::Aportuj() {

}

string Pies::Szczekaj() {

}

string Pies::MerdajOgonem() {

}

Pies Pies::Pies(string ras, string wil, string sierci) {

}

