//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"

class Pies : public Ssak {
public:
	string Aportuj();
	string Szczekaj();
	string MerdajOgonem();
	Pies Pies(string ras, string wil, string sierci);
private:
	string rasa;
	string wielkosc;
	string dlugosc_sierci;
};

#endif  //_PIES_H
