//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#include "Ssak.h"

string Ssak::WydawajDzwiek() {

}

Ssak Ssak::Ssak(int wag = 1, int zyc = 1, int por = 1) {

}

