//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 11.03.2024
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	string WydawajDzwiek();
	Ssak Ssak(int wag = 1, int zyc = 1, int por = 1);
private:
	int waga;
	int dlugosc_zycia;
	String sposob_poruszania_sie;
};

#endif  //_SSAK_H
